export const familyData = [
  { id: 1, pids: [2], name: "Lê Văn Nhạ", title: "Cao Tổ Khảo", gender: "male", deadDate: "25/08", img: "images/family-tree/menf1.jpg" },
  { id: 2, pids: [1], name: "Cố Nhạ bà", title: "Cao Tổ Tỷ", gender: "female", deadDate: "26/02", img: "images/family-tree/womenf1.jpg"  },
  { id: 3, mid: 2, fid: 1, name: "Lê Văn Nhạ(con)", title: "Tằng Tổ Bá Khảo", gender: "male", deadDate: "25/03", img: "images/family-tree/menf2-levannha.jpg"  },
  { id: 4, mid: 2, fid: 1, pids: [5, 6], name: "Lê Văn Tốn", title: "Tằng Tổ Khảo", gender: "male", deadDate: "09/04", img: "images/family-tree/menf2-levanton.jpg"  },
  { id: 5, pids: [4], name: "Bà Chí", title: "Tằng Tổ Tỷ", gender: "female", deadDate: "26/02", img: "images/family-tree/bachi.jpg"  },
  { id: 6, pids: [4], name: "Nguyễn Thị Chẩm", title: "Tằng Tổ Tỷ", gender: "female", deadDate: "19/06", img: "images/family-tree/nguyenthicham.jpg"  },
  { id: 7, mid: 5, fid: 4, name: "Lê Văn Chí", title: "Hiển Tổ Bá Khảo", gender: "male", deadDate: "09/04", img: "images/family-tree/levanchi.jpg"  },
  { id: 8, mid: 6, fid: 4, pids: [10], name: "Lê Văn Bường", title: "Hiển Tổ Khảo", gender: "male", deadDate: "30/02", img: "images/family-tree/ongbuong.jpg"  },
  { id: 9, mid: 6, fid: 4, name: "Lê Thị Chửng", title: "Bà Cô", gender: "female", deadDate: "08/07", img: "images/family-tree/lethichung.jpg"  },
  { id: 10, pids: [8], name: "Đậu Nguyễn Thị Em", title: "Hiển Tổ Tỷ", gender: "female", deadDate: "06/09", img: "images/family-tree/babuong.jpg"  },
  { id: 11, mid: 10, fid: 8, name: "Lê Thị Duệ", title: "Đường Cô", gender: "female", deadDate: "27/07", img: "images/family-tree/lethidue.jpg" },
  { id: 12, mid: 10, fid: 8, pids: [18], name: "Lê Trung Thành", title: "", gender: "male", img: "images/family-tree/o-thanh.jpg" },
  { id: 13, mid: 10, fid: 8, pids: [], name: "Lê Thị Loan", title: "", gender: "female" },
  { id: 14, mid: 10, fid: 8, pids: [19], name: "Lê Văn Lương", title: "", gender: "male" },
  { id: 15, mid: 10, fid: 8, pids: [], name: "Lê Thị Tâm", title: "", gender: "female" },
  { id: 16, mid: 10, fid: 8, pids: [20], name: "Lê Minh Lý", title: "", gender: "male", deadDate: "25/03", img: "images/family-tree/leminhly.jpg" },
  { id: 17, mid: 10, fid: 8, pids: [], name: "Lê Thị Lợi", title: "", gender: "female", img: "images/family-tree/lethiloi.jpg" },
  { id: 18, pids: [12], name: "Nguyễn Thị Nghiên", title: "", gender: "female" },
  { id: 19, pids: [14], name: "Nguyễn Thị Đức", title: "", gender: "female" },
  { id: 20, pids: [16], name: "Nguyễn Thị Phương", title: "", gender: "female", img: "images/family-tree/ba-phuong.jpg" },
  { id: 21, mid: 18, fid: 12, pids: [], name: "Lê Thị Hiền", title: "", gender: "female", img: "images/family-tree/hien.jpg" },
  { id: 22, mid: 18, fid: 12, pids: [], name: "Lê Thị Thảo", title: "", gender: "female", },
  { id: 23, mid: 18, fid: 12, pids: [], name: "Lê Thị Huyền", title: "", gender: "female", img: "images/family-tree/huyen.jpg"},
  { id: 24, mid: 18, fid: 12, pids: [], name: "Lê Thị Trang", title: "", gender: "female", img: "images/family-tree/trang.jpg" },
  { id: 25, mid: 18, fid: 12, pids: [26], name: "Lê Văn Đạt", title: "", gender: "male", img: "images/family-tree/dat.jpg" },
  { id: 26, pids: [25], name: "Nguyễn Như Quỳnh", title: "", gender: "female", img: "images/family-tree/quynh.jpg" },
  { id: 27, mid: 26, fid: 25, pids: [], name: "Lê An Như", title: "", gender: "female", img: "images/family-tree/babygirl.jpg" },
  { id: 28, mid: 26, fid: 25, pids: [], name: "Lê Diệp Chi", title: "", gender: "female", img: "images/family-tree/babygirl.jpg" },
  { id: 29, mid: 19, fid: 14, pids: [], name: "Lê Thị Hường", title: "", gender: "female", img: "images/family-tree/huong.jpg" },
  { id: 30, mid: 19, fid: 14, pids: [32], name: "Lê Văn Hải", title: "", gender: "male", img: "images/family-tree/hai.jpg" },
  { id: 31, mid: 19, fid: 14, pids: [33], name: "Lê Thanh Hưng", title: "", gender: "male", img: "images/family-tree/hung.jpg" },
  { id: 32, pids: [30], name: "Nguyễn Thị Lệ Thủy", title: "", gender: "female", img: "images/family-tree/thuytiu.jpg" },
  { id: 33, pids: [31], name: "Hoàng Thị Kim Liên", title: "", gender: "female", img: "images/family-tree/lien.jpg" },
  { id: 34, mid: 32, fid: 30, pids: [], name: "Lê Hải Bình", title: "", gender: "male", img: "images/family-tree/babyboy.jpg" },
  { id: 35, mid: 32, fid: 30, pids: [], name: "Lê Hải Đăng", title: "", gender: "male", img: "images/family-tree/babyboy.jpg" },
  { id: 36, mid: 33, fid: 31, pids: [], name: "Lê Quang Khải", title: "", gender: "male", img: "images/family-tree/babyboy.jpg" },
  { id: 37, mid: 33, fid: 31, pids: [], name: "Lê Minh Khuê", title: "", gender: "female", img: "images/family-tree/babygirl.jpg" },
  { id: 38, mid: 20, fid: 16, pids: [41], name: "Lê Văn Chương", title: "", gender: "male", img: "images/family-tree/chuong.jpg" },
  { id: 39, mid: 20, fid: 16, pids: [], name: "Lê Văn Dương", title: "", gender: "male", img: "images/family-tree/duong.jpg" },
  { id: 40, mid: 20, fid: 16, pids: [], name: "Lê Thị Trâm", title: "", gender: "male", img: "images/family-tree/tram.jpg" },
  { id: 41, pids: [38], name: "Trần Thị Nhung", title: "", gender: "female", img: "images/family-tree/nhung.jpg" },
  { id: 42, mid: 41, fid: 38, pids: [], name: "Lê Trần Nhật Long", title: "", gender: "male", img: "images/family-tree/babyboy.jpg" },
  { id: 43, mid: 41, fid: 38, pids: [], name: "Lê Minh Kiệt", title: "", gender: "male", img: "images/family-tree/babyboy.jpg" },
];