import type Post from '@/types/Post'

export const posts: Post[] = [
  {
    id: 10,
    avatar: 'images/avatar/comment.jpg',
    by: 'Phương Nhung',
    at: '2022 Mar 17 at 02:13 PM',
    ageCountTitle: 'Tora-kun',
    ageCount: '2022/03/17',
    location: '根本産婦人科',
    with: 'Tora-kun',
    content: `Em tên là LÊ TRẦN NHẬT LONG, ở nhà bố mẹ gọi em là Tora(tô-ra). Sau 2 ngày làm khổ mẹ thì hôm nay 2022/03/17 14:13 em đã chui ra. Em nặng 3 ký 2, dài 50 cm. Bố mẹ yêu em nhiều nhiều 💗💗💗`,
    images: ['images/post/10/1.jpg'],
    reaction: 0,
    comments: []
  },
  {
    id: 9,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Lê',
    at: '2021 Jun 03 at 12:00 AM',
    countUpText: 'WE GOT MARRIED',
    countUp: '2021/06/03 12:00:00',
    location: 'Đại sứ quán Việt Nam tại Nhật Bản',
    with: 'Phương Nhung',
    content: `Sau nhiều tháng tìm hiểu và chuẩn bị giấy tờ thủ tục cuối cùng cũng đến ngày đi đăng ký. Dậy từ 4h sáng để đi chuyến tàu sớm nhất nhưng lên tới nơi không có ai 😄. Sau nhiều giờ chờ đợi cuối cùng thủ tục cũng xong, chính thức trở thành vợ chồng. <span class="jp">これからよろしくね</span> 😙。`,
    images: ['images/post/7/img1.jpg'],
    reaction: 0,
    comments: []
  },
  {
    id: 8,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Lê',
    at: '2021 Mar 25 at 12:00 AM',
    location: 'Asakusa',
    with: 'Phương Nhung',
    content: `Sau ngày lễ đặt trầu, hai đứa quyết định thực hiện một bộ ảnh kỉ niệm với KIMONO. Địa điểm được lựa chọn là Asakusa, KIMONO cũng được thuê ở một cửa hàng tại đây. Một trải nghiệm thú vị đánh dấu sự kiện hai người chính thức qua lại.<br><i class="fas fa-camera-retro" style="font-size: 0.8em"></i> <a class="no-deco" href="https://fb.com/Sulerhy">Phạm Đức Hoàng</a>`,
    images: [
      'images/post/6/img1.jpg',
      'images/post/6/img2.jpg',
      'images/post/6/img3.jpg',
      'images/post/6/img4.jpg',
      'images/post/6/img5.jpg',
      'images/post/6/img6.jpg',
      'images/post/6/img7.jpg',
      'images/post/6/img8.jpg',
      'images/post/6/img9.jpg',
      'images/post/6/img10.jpg',
      'images/post/6/img11.jpg',
      'images/post/6/img12.jpg',
      'images/post/6/img13.jpg',
      'images/post/6/img14.jpg',
      'images/post/6/img15.jpg',
      'images/post/6/img16.jpg',
      'images/post/6/img17.jpg',
      'images/post/6/img18.jpg',
      'images/post/6/img19.jpg',
      'images/post/6/img20.jpg',
      'images/post/6/img21.jpg',
      'images/post/6/img22.jpg',
      'images/post/6/img23.jpg',
      'images/post/6/img24.jpg',
      'images/post/6/img25.jpg',
      'images/post/6/img26.jpg',
      'images/post/6/img27.jpg',
      'images/post/6/img28.jpg',
      'images/post/6/img29.jpg',
      'images/post/6/img30.jpg',
      'images/post/6/img31.jpg',
      'images/post/6/img32.jpg',
      'images/post/6/img33.jpg',
      'images/post/6/img34.jpg',
      'images/post/6/img35.jpg',
      'images/post/6/img36.jpg',
      'images/post/6/img37.jpg',
      'images/post/6/img38.jpg',
      'images/post/6/img39.jpg'
    ],
    reaction: 0,
    comments: []
  },
  {
    id: 7,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Lê',
    at: '2021 Mar 24 at 09:00 AM',
    location: 'Quang Sơn - Cẩm Quang',
    content: `Lễ đặt trầu cũng là bữa gặp mặt thân mật hai bên gia đình mặc dù không có mặt hai đứa. Từ đây đánh dấu hai đứa chính thức qua lại với nhau 😊.<br><i class="far fa-images" style="font-size: 0.8em"></i> Bên trái: Mẹ Hồng. Bên phải: Mẹ Phương.`,
    images: ['images/post/5/img1.jpg'],
    reaction: 0,
    comments: []
  },
  {
    id: 6,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Lê',
    at: '2020 Jul 26 at 01:00 PM',
    location: 'Yokohama',
    with: 'Phương Nhung',
    content: `Together to Yokohama`,
    images: [
      'images/post/8/img1.jpeg',
      'images/post/8/img2.jpeg',
      'images/post/8/img3.jpeg',
      'images/post/8/img4.jpeg',
      'images/post/8/img5.jpeg',
      'images/post/8/img6.jpeg',
      'images/post/8/img7.jpeg',
      'images/post/8/img8.jpeg',
      'images/post/8/img9.jpeg',
      'images/post/8/img10.jpeg',
      'images/post/8/img11.jpeg',
      'images/post/8/img12.jpeg',
      'images/post/8/img13.jpeg',
      'images/post/8/img14.jpeg'
    ],
    reaction: 0,
    comments: []
  },
  {
    id: 5,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Nhung',
    at: '2020 Jul 12 at 12:00 AM',
    location: 'Aidachi',
    with: 'Đạt Trinh',
    content: `Happy birth day to my honey 🎉`,
    images: [
      'images/post/9/img1.jpeg',
      'images/post/9/img6.jpeg',
      'images/post/9/img3.jpeg',
      'images/post/9/img4.jpeg',
      'images/post/9/img5.jpeg',
      'images/post/9/img7.jpeg',
      'images/post/9/img8.jpeg',
      'images/post/9/img2.jpeg'
    ],
    reaction: 0,
    comments: []
  },
  {
    id: 4,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Lê',
    at: '2020 Mar 20 at 05:20 PM',
    location: 'Sendai',
    with: 'Phương Nhung',
    content: `Sau thời gian dài quen biết, anh quết định đến thăm em cũng là lần hẹn hò đầu tiên của hai đứa. Một bước tiến dài trong mối quan hệ tình cảm của hai đứa.`,
    images: ['images/post/4/1.png'],
    reaction: 0,
    comments: []
  },
  {
    id: 3,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Lê',
    at: '2019 Dec 30 at 03:19 PM',
    location: 'Odaiba',
    with: 'Phương Nhung',
    content: `Bức hình chụp cùng nhau đầu tiên trong chuyến đi du lịch Odaiba. Cám ơn hai bạn Trung Quốc không biết tên.`,
    images: ['images/post/3/img1.jpg'],
    reaction: 0,
    comments: []
  },
  {
    id: 2,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Lê',
    at: '2019 Dec 29 at 06:10 PM',
    location: 'Tokyo Station',
    with: 'Phương Nhung',
    content: `Kỷ niệm lần gặp gỡ đầu tiên lúc chiều muộn ở ga Tokyo cùng vợ chồng a Đạt - Trinh.`,
    images: ['images/post/2/img1.jpg'],
    reaction: 0,
    comments: []
  },
  {
    id: 1,
    avatar: 'images/avatar/comment.jpg',
    by: 'Chương Lê',
    at: '2019 Aug 17 at 11:35 PM',
    content: `Hi Nhung, anh tên là Chương, rất vui vì được biết em 😊 <span class="jp">よろしくね。</span>
    <br>※ Đặc biệt cảm ơn ông bà mai <a class="no-deco" href="https://www.facebook.com/longnvht" target="_blank">Long</a>-<a class="no-deco" href="https://www.facebook.com/vo.thuong.773" target="_blank">Hoài</a> 🥰`,
    images: ['images/post/1/img1.jpg'],
    reaction: 0,
    comments: []
  }
]
